<!DOCTYPE>
<html>
<head>
    <meta charset="UTF-8">
    <title>Department Management</title>
</head>
<body>
<h1>Деталі кафедри</h1>
<div>
    <strong>Назва:</strong> ${department.name}<br>
    <strong>Title:</strong> ${department.title}<br>
    <strong>Телефон:</strong> ${department.phone}<br>
    <strong>Аудиторія:</strong> ${department.classroom}
</div>
<div>
    <a href="/departments">Повернутись до списку кафедр</a>
</div>
</body>
</html>